### ISSUE TITLE
Add sleep

### ISSUE THREAD

**Issue by badeend** [WebAssembly/wasi-clocks#18]
Like:
```rs
sleep: func(duration: u64) -> future<unit>
```

Returns a future that completes after `duration` has elapsed.

Thoughts?

**Comment by sunfishcode** [comment]
This is the intention for the timer functions. The idea is that one creates a timer with [new-timer](https://github.com/WebAssembly/wasi-clocks/blob/main/wasi-clocks.wit.md#new-timer) and then use [cabi wait](https://docs.google.com/presentation/d/1MNVOZ8hdofO3tI0szg_i-Yoy0N2QPU2C--LzVuoGSlE/edit#slide=id.g1270ef7d5b6_0_662) to wait for it to complete.

**Comment by sunfishcode** [comment]
Hmm, it's a good point though that this should now be a future rather than a resource. I'll submit a PR for that.

**Comment by sunfishcode** [comment]
I've now submitted https://github.com/WebAssembly/wasi-clocks/pull/19 introducing the use of a `future`, which allows it to work with the new `cabi wait` design.

**Comment by badeend** [comment]
Nice. That addresses all my needs, so nothing left for me to discuss here. Closing this while awaiting #19
