### ISSUE TITLE
Should we have a `duration` type distinct from `instant`?

### ISSUE THREAD

**Issue by pchickey** [WebAssembly/wasi-clocks#52]
Presently, in the monotonic clock interface, duration is conflated with a timestamp, with a boolean in the `subscribe` function indicating whether the instant actually represents a duration.

I believe we should distinguish between these in the type system, and rather than use a boolean, expose two different subscribe functions, as shown below.

One advantage of this is that other WASI libraries can then `use wasi:clocks/monotonic-clock.{duration};` as a standard representation of duration. For instance, right now wasi-http uses a u32 to represent at timeout in milliseconds. It would be nice to point to one single duration type and say to always use that one unless the problem domain insists otherwise.

```diff
diff --git a/crates/wasi-http/wit/deps/clocks/monotonic-clock.wit b/crates/wasi-http/wit/deps/clocks/monotonic-clock.wit
index d9ac7cb3f..a6e2574bf 100644
--- a/crates/wasi-http/wit/deps/clocks/monotonic-clock.wit
+++ b/crates/wasi-http/wit/deps/clocks/monotonic-clock.wit
@@ -14,6 +14,9 @@ interface monotonic-clock {
     /// A timestamp in nanoseconds.
     type instant = u64;

+    /// A duration in nanoseconds.
+    type duration = u64;
+
     /// Read the current value of the clock.
     ///
     /// The clock is monotonic, therefore calling this function repeatedly will
@@ -25,8 +28,13 @@ interface monotonic-clock {

     /// Create a `pollable` which will resolve once the specified time has been
     /// reached.
-    subscribe: func(
+    subscribe_instant: func(
         when: instant,
-        absolute: bool
+    ) -> pollable;
+
+    /// Create a `pollable` which will resolve once the given duration
+    /// has elapsed, starting at the time this function is called.
+    subscribe_duration: func(
+        when: duration,
     ) -> pollable;
     ```

**Comment by sunfishcode** [comment]
Having `absolute` be a dynamic flag comes from CloudABI, which comes from POSIX `clock_nanosleep` which has a dynamic `TIMER_ABSTIME` flag. Could we guess that most users using `clock_nanosleep` and/or calling the WASI API directly are using a constant value for the `TIMER_ABSTIME`/`CLOCK_ABSTIME` flag?

**Comment by sunfishcode** [comment]
I agree.
